BaSP- TG-6: Project table - resources list
BaSP-a2022/alfon-b-trackgenix-app pull request #1
Opened 2022-10-31 12:42 UTC by pabloschivazappa

2022-11-02 18:51 UTC, leimeter-joaquin requested changes

2022-11-02 18:51 UTC, leimeter-joaquin commented on package.json
> +    "react-scripts": "^5.0.1",
Remove this change to package.json

2022-11-02 19:01 UTC, pabloschivazappa commented on package.json
> +    "react-scripts": "^5.0.1",
Done

2022-11-04 19:06 UTC, leimeter-joaquin approved these changes
There are some issues, but we can re iterate on them in the following week

2022-11-04 19:12 UTC, leimeter-joaquin requested changes

2022-11-04 19:12 UTC, leimeter-joaquin commented on src/Components/Projects/Form/index.js
> +                    value={employees.map((e) => e.employee).map((id) => id._id)}
```suggestion
                    value={employees[index]._id}
```

Check if this works better. I cannot write into the employee id input. 
Also, for next week, we should work on showing the user the available employees and passing a name on the input, not an id.

2022-11-04 19:41 UTC, pabloschivazappa commented on src/Components/Projects/Form/index.js
> +                    value={employees.map((e) => e.employee).map((id) => id._id)}
Done with "value={employees[index].employee._id}"

2022-11-04 19:44 UTC, leimeter-joaquin approved these changes

2022-11-05 13:46 UTC, Alfondalix submitted a review, later dismissed

2022-11-05 22:12 UTC, eialyafe commented
All functionalities are ok edit, delete, and create. All success or error messsage are displeyed. 
There were just syntax mistakes:
 
1) All error messages when editting projects says: "cannot CREATE"
 
2) All error messages when create or edit with some employees fields empty says: "Cannot create project: "employees[0].employee"

 3) When you try create a project with start date grater than end date message displayed is: "Cannot create project: "endDate" must be greater than "ref:startDate", just need to be deleted "ref"

I made a doc  with all messages error thas had a problem, and with all testes made. You can check it here 
https://docs.google.com/spreadsheets/d/1q_hpcj_gpgHIVMhLFIMpEQzGRzcBr-4YIwoG4fL3cfo/edit?usp=sharing

2022-11-06 14:21 UTC, amilcarHernandez24 submitted a review, later dismissed

2022-11-06 14:57 UTC, amilcarHernandez24 approved these changes
Well done.

2022-11-06 15:00 UTC, leimeter-joaquin approved these changes

2022-11-06 15:00 UTC, merged