BaSP-TG-08: Task table - Resources list
BaSP-a2022/alfon-b-trackgenix-app pull request #2
Opened 2022-11-01 04:44 UTC by TomasBettini

2022-11-02 23:05 UTC, Juancapp commented on src/Components/Tasks/Form/index.js
> +  if (idRegEx.test(urlID)) {
Put the IF conditional into the UseEffect

2022-11-02 23:06 UTC, Juancapp submitted a review, later dismissed
Nice code!!!

2022-11-02 23:12 UTC, Juancapp submitted a review, later dismissed
Nice code!!!

2022-11-04 13:35 UTC, juliancit0 submitted a review, later dismissed
Good job!

2022-11-04 19:29 UTC, leimeter-joaquin requested changes

2022-11-04 19:29 UTC, leimeter-joaquin commented on src/Components/Tasks/Form/index.js
> +            <a href={'http://localhost:3000/tasks'}>
don't link to localhost use the env variable

2022-11-04 20:20 UTC, leimeter-joaquin approved these changes

2022-11-05 13:48 UTC, Alfondalix approved these changes

2022-11-05 16:02 UTC, disimoneleandro commented
QA pased!

2022-11-05 16:03 UTC, merged