BaSP-TG-42: Redux - Super Admin
BaSP-a2022/alfon-b-trackgenix-app pull request #26
Opened 2022-11-15 02:22 UTC by mgriolfo-g

Implementation of redux over the Super Admin features. Based on Admin Redux and other implementations, developed cooperatively over the past couple of days!

2022-11-15 02:58 UTC, JuliBalcaza approved these changes
It's nice that you added uppercases

2022-11-15 02:59 UTC, JuliBalcaza commented
approved by QA, as a suggestion remember to add a message to the list when it is empty ("Empty list" or "No Super Admins Yet").

2022-11-15 13:30 UTC, mgriolfo-g commented
> approved by QA, as a suggestion remember to add a message to the list when it is empty ("Empty list" or "No Super Admins Yet").

Thanks for the suggestion! Pushed changes that made that state unreachable, it should appear on Admins and Super Admins now! Please check it again 😄

2022-11-16 00:55 UTC, juliancit0 requested changes

2022-11-16 00:55 UTC, juliancit0 commented on src/redux/superAdmins/thunks.js
> +        console.log(data);
```suggestion
```
You should delete this console.log()

2022-11-16 00:55 UTC, juliancit0 commented on src/redux/superAdmins/thunks.js
> +        console.log(data);
```suggestion
```
And this too

2022-11-16 15:16 UTC, mgriolfo-g commented on src/redux/superAdmins/thunks.js
> +        console.log(data);
Done, thanks again 😄

2022-11-16 20:57 UTC, juliancit0 approved these changes

2022-11-16 20:58 UTC, TomasBettini approved these changes
Good job

2022-11-17 03:32 UTC, merged