BaSP-TG-47: tasks - put and post
BaSP-a2022/alfon-b-trackgenix-app pull request #28
Opened 2022-11-15 18:45 UTC by amilcarHernandez24

2022-11-15 18:51 UTC, disimoneleandro submitted a review, later dismissed
QA Approved!

2022-11-15 18:51 UTC, disimoneleandro commented
QA Approved!

2022-11-15 19:04 UTC, pabloschivazappa submitted a review, later dismissed
Nice work!

2022-11-16 00:49 UTC, juliancit0 requested changes

2022-11-16 00:49 UTC, juliancit0 commented on src/Components/Tasks/Form/index.js
> +    console.log(descriptionValue);
```suggestion
```
You should delete this console log

2022-11-16 19:46 UTC, amilcarHernandez24 commented on src/Components/Tasks/Form/index.js
> +    console.log(descriptionValue);
Thank juli, I'll do it.

2022-11-16 20:57 UTC, juliancit0 approved these changes

2022-11-16 21:03 UTC, Juancapp approved these changes
Oh yeah!

2022-11-16 21:04 UTC, TomasBettini approved these changes
Nice work!

2022-11-16 21:05 UTC, merged