BaSP-TG-01: Super Admin table - Resources List
BaSP-a2022/alfon-b-trackgenix-app pull request #3
Opened 2022-11-01 04:52 UTC by Juancapp

**Show a table with the list of resources of the assigned entity, saved in the database.
For each row, you must be able to:**

- Edit an item.
- Delete an item.
- Show success and error messages.

 **For the whole table:**
- Create a redirect button to 'Add feature'

2022-11-02 18:50 UTC, leimeter-joaquin requested changes

2022-11-02 18:50 UTC, leimeter-joaquin commented on package.json
>      "web-vitals": "^1.1.2"
Remove every change to package.json

2022-11-02 19:01 UTC, leimeter-joaquin requested changes

2022-11-02 19:01 UTC, leimeter-joaquin commented on src/Components/SuperAdmins/Form/index.js
> +  if (idRegEx.test(product)) {
Place the if inside the useEffect

2022-11-02 21:23 UTC, TomasBettini commented on src/Components/SuperAdmins/Form/index.js
> +      console.log(data);
You must delete this console.log

2022-11-02 21:23 UTC, TomasBettini submitted a review, later dismissed
Nice code!

2022-11-03 22:42 UTC, juliancit0 requested changes

2022-11-04 01:30 UTC, juliancit0 submitted a review, later dismissed

2022-11-04 19:33 UTC, leimeter-joaquin requested changes
Fix that, everything else seems great!

2022-11-04 19:33 UTC, leimeter-joaquin commented on src/Components/SuperAdmins/Form/index.js
> +            <a href={'http://localhost:3000/super-admins'}>
use the env variable, not localhost

2022-11-04 20:12 UTC, leimeter-joaquin submitted a review, later dismissed

2022-11-05 13:49 UTC, Alfondalix submitted a review, later dismissed

2022-11-06 12:11 UTC, leimeter-joaquin approved these changes

2022-11-06 14:17 UTC, amilcarHernandez24 approved these changes
Good job.

2022-11-06 14:18 UTC, merged