BaSP-TG/55 project table - delete and put functions
BaSP-a2022/alfon-b-trackgenix-app pull request #40
Opened 2022-11-20 02:14 UTC by Juancapp

2022-11-20 15:00 UTC, leimeter-joaquin requested changes

2022-11-20 17:24 UTC, eialyafe submitted a review, later dismissed
Approved, all functionalities described are Ok. And works as expected

2022-11-21 23:19 UTC, juliancit0 approved these changes
Perfect

2022-11-22 01:03 UTC, TomasBettini approved these changes
Nice work!

2022-11-22 01:03 UTC, merged