BaSP-TG-05: Timesheets table - Resources list
BaSP-a2022/alfon-b-trackgenix-app pull request #5
Opened 2022-11-01 21:39 UTC by juliancit0

In this PR I created React components to show a table with the list of resources from timesheets saved in the database.

For each row, you must be able to:
- Edit a timesheet.
- Delete a timesheet.

For the whole table I created a redirect button to 'forms' section that contains 'Add feature' to create a timesheet.

2022-11-02 21:28 UTC, TomasBettini commented on src/Components/TimeSheets/index.jsx
> +    if (confirm('Are you sure that you want to delete the task?')) {
You must change the message "delete the task" to "delete the timesheet"

2022-11-02 21:31 UTC, TomasBettini submitted a review, later dismissed
Good job!

2022-11-03 20:36 UTC, juliancit0 commented on src/Components/TimeSheets/index.jsx
> +    if (confirm('Are you sure that you want to delete the task?')) {
Hahahha, solved!

2022-11-05 19:42 UTC, leimeter-joaquin requested changes
When getting the list of timesheets I get this error on console:
`TypeError: Cannot read properties of null (reading 'name') at G (ListItem.jsx:14:25)`
Try to check for undefined or null values with ?. before using them

2022-11-06 12:12 UTC, leimeter-joaquin submitted a review, later dismissed

2022-11-06 15:33 UTC, leimeter-joaquin approved these changes

2022-11-06 15:34 UTC, Alfondalix approved these changes

2022-11-06 15:35 UTC, merged

2022-11-06 15:46 UTC, disimoneleandro commented
Approved for QA!