BaSP-TG-05: Admins table
BaSP-a2022/alfon-b-trackgenix-app pull request #6
Opened 2022-11-02 02:17 UTC by amilcarHernandez24

2022-11-02 20:58 UTC, TomasBettini commented
The name of your PR is wrong, your assigned ticket is 09 and I don't know why but the deploy to vercel has a problem

2022-11-02 21:00 UTC, TomasBettini commented on src/Components/Admins/FormAdmins/index.js
> +      console.log(adminInput);
You must delete this console.log

2022-11-02 21:05 UTC, amilcarHernandez24 commented on src/Components/Admins/FormAdmins/index.js
> +      console.log(adminInput);
thanks, I'll

2022-11-02 21:10 UTC, TomasBettini commented on src/Components/Admins/index.js
> +  // eslint-disable-next-line no-unused-vars
You must delete this comment

2022-11-02 21:10 UTC, TomasBettini approved these changes
I think you still have to add a modal to show the success and error messages, and also add a bit of css to the form and the list, but I see that the functionalities are all good

2022-11-02 21:21 UTC, amilcarHernandez24 commented on src/Components/Admins/index.js
> +  // eslint-disable-next-line no-unused-vars
Thanks, I'll delete it.

2022-11-03 22:47 UTC, juliancit0 requested changes

2022-11-03 22:49 UTC, amilcarHernandez24 commented on src/Components/Admins/index.js
> +  };
Thanks Juli. I'll change that

2022-11-04 01:31 UTC, juliancit0 submitted a review, later dismissed

2022-11-04 01:35 UTC, juliancit0 commented on src/Components/Admins/index.js
> +  };
Nice!

2022-11-05 17:36 UTC, mgriolfo-g commented on src/Components/Admins/index.js
> +      if (response.ok) {
A filter for a deleted element should be added after the request of its deletion (or when its deletion is confirmed), in order to keep the page dynamic and avoiding errors. Try to add a filter like this one:
`        const newAdmins = admins.filter((admin) => admin._id !== id);
        setAdmins(newAdmins);`

2022-11-05 20:21 UTC, amilcarHernandez24 commented on src/Components/Admins/index.js
> +      if (response.ok) {
I just fixed it

2022-11-05 20:27 UTC, leimeter-joaquin approved these changes

2022-11-05 20:56 UTC, TomasBettini approved these changes
Nice job!

2022-11-06 14:00 UTC, leimeter-joaquin approved these changes

2022-11-06 14:08 UTC, merged